name: nodeseek鸡腿签到

on:
  push:
    branches:
      - main
  schedule:
    - cron: '00 16 * * *'  # 北京时间 00:00 (UTC+8)，对应UTC时间 16:00
  workflow_dispatch:

jobs:
  run-nodeseek-sign:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码仓库
        uses: actions/checkout@v3
      
      - name: 配置Python环境
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.8'

      - name: 安装依赖包
        run: pip install curl_cffi requests

      - name: 调试环境变量
        run: |
          echo "检查环境变量是否已定义:"
          if [ -n "$ACCOUNTS" ]; then echo "ACCOUNTS 已定义"; else echo "ACCOUNTS 未定义"; fi
          if [ -n "$API_BASE_URL" ]; then echo "API_BASE_URL 已定义"; else echo "API_BASE_URL 未定义"; fi
          if [ -n "$CLIENTT_KEY" ]; then echo "CLIENTT_KEY 已定义"; else echo "CLIENTT_KEY 未定义"; fi
        env:
          ACCOUNTS: ${{ secrets.ACCOUNTS }}
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          CLIENTT_KEY: ${{ secrets.CLIENTT_KEY }}

      - name: 直接设置所有必要变量
        run: |
          echo 'ACCOUNTS=[{"username":"辣叔叔","password":"haozi1781"},{"username":"昆吾断鸿","password":"haozi1781"}]' >> $GITHUB_ENV
          echo 'API_BASE_URL=http://123.120.59.145:3000' >> $GITHUB_ENV
          echo 'CLIENTT_KEY=haozi1781' >> $GITHUB_ENV
          echo 'SOLVER_TYPE=turnstile' >> $GITHUB_ENV

      - name: 运行签到脚本
        env:
          # 使用直接设置的变量
          ACCOUNTS: ${{ env.ACCOUNTS }}
          API_BASE_URL: ${{ env.API_BASE_URL }}
          CLIENTT_KEY: ${{ env.CLIENTT_KEY }}
          SOLVER_TYPE: ${{ env.SOLVER_TYPE }}
          
          # 通知推送配置
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          TG_THREAD_ID: ${{ secrets.TG_THREAD_ID }}
        run: python nodeseek_sign.py
